# Wine Dataset Analysis

## Project Overview

This project explores a wine dataset using Python and Pandas.

The analysis focuses on data cleaning, missing values, wine varieties, countries, wineries, prices, and wine ratings.

#1.Data Loading

In [90]:
import pandas as pd
import numpy as np
df = pd.read_csv("Wine_data.csv")
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

#2.Data Overview

In [91]:
df.shape

(129971, 14)

In [92]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             129971 non-null  int64
 1   country                129908 non-null  str
 2   description            129971 non-null  str
 3   designation            92506 non-null   str
 4   points                 129971 non-null  int64
 5   price                  120975 non-null  float64
 6   province               129908 non-null  str
 7   region_1               108724 non-null  str
 8   region_2               50511 non-null   str
 9   taster_name            103727 non-null  str
 10  taster_twitter_handle  98758 non-null   str
 11  title                  129971 non-null  str
 12  variety                129970 non-null  str
 13  winery                 129971 non-null  str
dtypes: float64(1), int64(2), str(11)
memory usage: 13.9 MB

#3.Data Cleaning

In [93]:
df.isnull().sum()

Unnamed: 0                   0
country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

In [94]:
df.isnull().mean() * 100

Unnamed: 0                0.000000
country                   0.048472
description               0.000000
designation              28.825661
points                    0.000000
price                     6.921544
province                  0.048472
region_1                 16.347493
region_2                 61.136715
taster_name              20.192197
taster_twitter_handle    24.015357
title                     0.000000
variety                   0.000769
winery                    0.000000
dtype: float64

In [95]:
df = df.drop("Unnamed: 0", axis=1)
df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [96]:
df.duplicated().sum()

np.int64(9983)

#4.Statistical Overview

In [97]:
df.describe()

              points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

#5.Categorical Analysis

In [98]:
df["region_2"].value_counts().head(10)

region_2
Central Coast        11065
Sonoma                9028
Columbia Valley       8103
Napa                  6814
Willamette Valley     3423
California Other      2663
Finger Lakes          1777
Sierra Foothills      1462
Napa-Sonoma           1169
Central Valley        1062
Name: count, dtype: int64

In [99]:
df["country"].value_counts().head(10)

country
US           54504
France       22093
Italy        19540
Spain         6645
Portugal      5691
Chile         4472
Argentina     3800
Austria       3345
Australia     2329
Germany       2165
Name: count, dtype: int64

In [100]:
df.groupby("country")["points"].mean().sort_values(ascending=False).head(10)

country
England       91.581081
India         90.222222
Austria       90.101345
Germany       89.851732
Canada        89.369650
Hungary       89.191781
China         89.000000
France        88.845109
Luxembourg    88.666667
Australia     88.580507
Name: points, dtype: float64

In [101]:
df["variety"].value_counts().head(10)

variety
Pinot Noir                  13272
Chardonnay                  11753
Cabernet Sauvignon           9472
Red Blend                    8946
Bordeaux-style Red Blend     6915
Riesling                     5189
Sauvignon Blanc              4967
Syrah                        4142
Rosé                         3564
Merlot                       3102
Name: count, dtype: int64

#6.Price & Points Analysis

In [102]:
df[["price", "points"]].corr()

           price    points
price   1.000000  0.416167
points  0.416167  1.000000

In [103]:
df.groupby("points")["price"].mean().sort_values(ascending=False).head(10)

points
100    485.947368
99     284.214286
98     245.492754
97     207.173913
96     159.292531
95     109.235420
94      81.436938
93      63.112216
92      51.037763
91      43.224252
Name: price, dtype: float64

#7.Varitey Analysis

In [104]:
df.groupby("variety")["points"].mean().sort_values(ascending=False).head(10)

variety
Tinta del Pais         95.000000
Gelber Traminer        95.000000
Terrantez              95.000000
Bual                   94.142857
Riesling-Chardonnay    94.000000
Sercial                94.000000
Blauburgunder          93.000000
Ramisco                93.000000
Garnacha-Cariñena      93.000000
Muscadelle             92.500000
Name: points, dtype: float64

In [105]:
df.groupby("variety")["points"].agg(["mean", "count"]).sort_values("mean", ascending=False).head(10)

                          mean  count
variety
Tinta del Pais       95.000000      2
Gelber Traminer      95.000000      1
Terrantez            95.000000      1
Bual                 94.142857      7
Riesling-Chardonnay  94.000000      1
Sercial              94.000000      1
Blauburgunder        93.000000      1
Ramisco              93.000000      1
Garnacha-Cariñena    93.000000      1
Muscadelle           92.500000     10

In [106]:
df.groupby("variety")["price"].mean().sort_values(ascending=False).head(10)

variety
Ramisco             495.000000
Terrantez           236.000000
Francisa            160.000000
Rosenmuskateller    150.000000
Malbec-Cabernet     113.333333
Tinta Negra Mole    112.000000
Muscadelle          111.200000
Bual                100.000000
Debit                98.333333
Cabernet-Shiraz      83.500000
Name: price, dtype: float64

In [107]:
df.groupby("variety")["price"].agg(["mean", "count"]).sort_values("mean", ascending=False).head(10)

                        mean  count
variety
Ramisco           495.000000      1
Terrantez         236.000000      1
Francisa          160.000000      1
Rosenmuskateller  150.000000      1
Malbec-Cabernet   113.333333      3
Tinta Negra Mole  112.000000      1
Muscadelle        111.200000     10
Bual              100.000000      6
Debit              98.333333      3
Cabernet-Shiraz    83.500000      2

#8.Winery Analysis

In [108]:
df["winery"].value_counts().head(10)

winery
Wines & Winemakers       222
Testarossa               218
DFJ Vinhos               215
Williams Selyem          211
Louis Latour             199
Georges Duboeuf          196
Chateau Ste. Michelle    194
Concha y Toro            164
Columbia Crest           159
Kendall-Jackson          130
Name: count, dtype: int64

In [109]:
df.groupby("winery")["price"].mean().sort_values(ascending=False).head(10)

winery
Château les Ormes Sorbet         3300.000000
Château Pétrus                   2250.000000
Domaine du Comte Liger-Belair    1488.750000
Château Cheval Blanc              825.000000
Château d'Yquem                   800.000000
Masseto                           587.500000
Château Laville Haut-Brion        580.000000
Château Haut-Brion                571.700000
Château La Mission Haut-Brion     545.750000
Château Ausone                    506.666667
Name: price, dtype: float64